# Data Preprocessing Tools

- **Importing Libraries:** Essential Python libraries including NumPy, Matplotlib, and Pandas are imported for handling arrays, plotting graphs, and manipulating datasets respectively.

- **Importing the Dataset:** The process of importing a dataset using Pandas is demonstrated, focusing on separating it into independent features (`X`) and the dependent target variable (`y`).

- **Splitting the Dataset:** The dataset is split into Training and Test sets using scikit-learn's `train_test_split` function, an essential step for model evaluation.

- **Handling Missing Data:** Techniques for handling missing data are covered, highlighting the importance of proper data imputation.

- **Encoding Categorical Data:** The notebooks discuss encoding categorical variables to convert them into a machine-readable format, using methods like OneHotEncoder and LabelEncoder.

- **Feature Scaling:** Feature scaling methods, especially standardization, are emphasized to ensure all features contribute equally to the model's performance.

- **Print Transformed Data:** Finally, the transformed feature sets are printed to verify the effectiveness of the preprocessing steps.

## Importing the libraries

In [15]:
import numpy as np # numpy allows us to work with arrays
import matplotlib.pyplot as plt #matplot allows us to plot charts
import pandas as pd #pandas allows to import datasets

## Importing the dataset

In [16]:
dataset = pd.read_csv('data/pre_data.csv')
X = dataset.iloc[:, :-1].values # Features or independent variables
y = dataset.iloc[:, -1].values # Dependent variable or result

In [17]:
print(X) #the matrix of features

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [18]:
print(y) # the dependent variable vector

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

- we will be handling missing data by changing it with the average of all the values, we could have used median, high frequency values, etc.

In [19]:
# Import the SimpleImputer class from scikit-learn for handling missing values.
from sklearn.impute import SimpleImputer  
# Create an imputer object that replaces missing values with the mean of the remaining values in the column.
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')  
# Fit the imputer to the columns of interest (second and third columns) in the dataset to calculate the mean values for each.
imputer.fit(X[:, 1:3])  
# Transform the dataset by replacing missing values with the calculated means in the specified columns.
X[:, 1:3] = imputer.transform(X[:, 1:3])  

In [20]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [21]:
# Import the ColumnTransformer class from scikit-learn to apply transformations to columns of an array or pandas DataFrame.
from sklearn.compose import ColumnTransformer
# Import the OneHotEncoder class from scikit-learn for encoding categorical features as a one-hot numeric array.
from sklearn.preprocessing import OneHotEncoder

# Create a ColumnTransformer object to apply a OneHotEncoder to the first column of the dataset; leave the rest of the columns unchanged.
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# Apply the ColumnTransformer to the dataset, converting it to an array, and overwrite the original dataset with the transformed data.
X = np.array(ct.fit_transform(X))

In [22]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [23]:
# Import the LabelEncoder class from scikit-learn for encoding labels with value between 0 and n_classes-1.
from sklearn.preprocessing import LabelEncoder

# Create an instance of the LabelEncoder class.
le = LabelEncoder()

# Fit the label encoder and return encoded labels for the target variable y.
y = le.fit_transform(y)

In [24]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [25]:
# Import the train_test_split function from scikit-learn to split arrays or matrices into random train and test subsets.
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets, with 20% of the data used as the test set. 
# The random_state parameter ensures reproducibility of the split.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [26]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [27]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [28]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [29]:
print(y_test)

[0 1]


## Feature Scaling

In [30]:
# Import the StandardScaler class from scikit-learn for standardizing features by removing the mean and scaling to unit variance.
from sklearn.preprocessing import StandardScaler

# Create an instance of the StandardScaler class.
sc = StandardScaler()

# Fit the StandardScaler to the training data starting from the fourth column onwards and transform these columns.
# This standardizes the features by making them have a mean of 0 and a standard deviation of 1.
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

# Transform the testing data starting from the fourth column onwards using the same scaler (mean and std) as the training data.
# This ensures that the test data is scaled in the same way as the training data.
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [31]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [32]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
